name: Blackduck Scan Build
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/[1-9]')
    steps:
      - name: Checking out main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
