name: Blackduck Scan Build
on:
  push:
    tags:
      - '^([1-9]\d{3})\.(\d{2})\.(\d{1})-RELEASE$'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checking out main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
