name: Blackduck Scan Build
on:
  push:
    tags:
      - "[1-9][0-9][0-9][0-9].[0-1][0-9].0-RELEASE"
jobs:
  build:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '^refs/tags/\d{4}\.(0[1-9]|1[0-2])\.0-RELEASE$')
    steps:
      - name: Checking out ${{ github.ref_name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
