name: Blackduck Scan Build
on:
  push:
    tags:
      - "[1-9][0-9][0-9][0-9].[0-9].[1-9][0-2]?.0"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checking out ${{ github.ref_name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
      - name: Print ref
        run: echo ${{ github.ref }}
        
