name: My Workflow

on:
  push:
    branches:
      - main
      - '[1-9][0-9][0-9][0-9].*.0.0-RELEASE-*'
    tags:
      - '[1-9][0-9][0-9][0-9].*.0.0'
concurrency:
  group: my-workflow-group
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Input 1"
      - name: Step 2
        run: echo "Input 2"
