name: Setup Python Version
on: [push]
jobs:
  install-python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
