name: Setup Custom Python Version
on: [push]
jobs:
  install-python-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
