name: Setup Custom Python Version
on:
  push:
    branches:
      - 'main'
jobs:
  install-python-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
      - name: Install Pip Custom Version
        run: pip install --upgrade pip==21.2.3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Change Directory
        run: cd tests
      - name: Run Tests
        run: coverage run -m pytest --durations=5 -s -p no:warnings src
      - name: Test Coverage Report
        run: coverage report -m
