name: Setup Python Version
on: [push]
jobs:
  install-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
